'use strict';

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rootDir = path.resolve(__dirname, '..');
const pluginsDir = path.join(rootDir, 'src', 'plugins');
const loaderPath = path.join(rootDir, 'src', 'core', 'app', 'rendererPluginLoader.js');

function slugify(input) {
  return input
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function toTitleCaseFromSlug(slug) {
  return slug
    .split('-')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

function assert(condition, message) {
  if (!condition) {
    console.error(`[plugin:new] ${message}`);
    process.exit(1);
  }
}

function writeFileSafe(filePath, content) {
  fs.writeFileSync(filePath, content, { flag: 'wx' });
}

function createPluginFiles(slug, displayName) {
  const pluginDir = path.join(pluginsDir, slug);
  assert(!fs.existsSync(pluginDir), `Plugin folder already exists: src/plugins/${slug}`);

  const folders = [
    pluginDir,
    path.join(pluginDir, 'components'),
    path.join(pluginDir, 'pages'),
    path.join(pluginDir, 'hooks'),
    path.join(pluginDir, 'services'),
    path.join(pluginDir, 'slots'),
    path.join(pluginDir, 'events'),
    path.join(pluginDir, 'styles'),
    path.join(pluginDir, 'assets'),
  ];

  folders.forEach((dir) => fs.mkdirSync(dir, { recursive: true }));

  // Keep generated folders visible/committable even before first file is added.
  folders.slice(1).forEach((dir) => {
    writeFileSafe(path.join(dir, '.gitkeep'), '');
  });

  const pluginJson = `{
  "id": "${slug}",
  "name": "${displayName}",
  "version": "1.0.0",
  "enabled": true,
  "description": "${displayName} plugin"
}\n`;

  const indexJsx = `/**
 * ${slug}/index.jsx
 *
 * Plugin entry point.
 * Only keep registration wiring here.
 * Put real business logic inside services/hooks/components and call it from here.
 */
export default async function register(api) {
  api.logger.info('${displayName} plugin activated');

  // Way 1: Replace a component
  // api.registerComponent('cart.DiscountRow', MyDiscountRow);

  // Way 2: Inject into a slot
  // api.registerSlot('pos.cart.footer', {
  //   id: '${slug}.cart-footer',
  //   component: MyCartFooter,
  //   order: 100,
  // });

  // Way 3: Wrap a component
  // api.wrapComponent('ProductCard', MyProductCardWrapper);

  // Way 4: Register a new screen/route
  // api.registerScreen('${slug}', {
  //   label: '${displayName}',
  //   icon: 'PLG',
  //   component: My${displayName.replace(/\s+/g, '')}Screen,
  // });
}
`;

  const readme = `# ${displayName}

Generated by \`npm run plugin:new -- "${displayName}"\`.

## What to edit

- \`index.jsx\`: Register hooks/components/screens using the plugin API.
- \`services/\`: Business rules and data logic.
- \`hooks/\`: Hook handlers.
- \`components/\`, \`pages/\`, \`slots/\`: UI code.

## Registered in loader

This plugin is auto-added to \`src/core/app/rendererPluginLoader.js\`.
Disable/uninstall by removing its tuple from ACTIVE_RENDERER_PLUGINS.
`;

  const permissions = `export const pluginPermissions = {
  // Define plugin-scoped permissions here when needed.
  // Example: CAN_APPLY_DISCOUNT: 'canApplyDiscount',
};
`;

  writeFileSafe(path.join(pluginDir, 'plugin.json'), pluginJson);
  writeFileSafe(path.join(pluginDir, 'index.jsx'), indexJsx);
  writeFileSafe(path.join(pluginDir, 'README.md'), readme);
  writeFileSafe(path.join(pluginDir, 'permissions.js'), permissions);
}

function wirePluginIntoRendererLoader(slug, displayName) {
  assert(fs.existsSync(loaderPath), 'rendererPluginLoader.js not found');

  let loader = fs.readFileSync(loaderPath, 'utf8');

  // Normalize old path style to the correct relative path from src/core/app -> src/plugins
  loader = loader
    .replace(/\(\)\s*=>\s*import\('\.\.\/plugins\//g, "() => import('../../plugins/")
    .replace(/\(\)\s*=>\s*import\("\.\.\/plugins\//g, '() => import("../../plugins/');

  if (loader.includes(`id: '${slug}'`) || loader.includes(`id: "${slug}"`)) {
    fs.writeFileSync(loaderPath, loader);
    console.log(`[plugin:new] Loader already contains plugin id "${slug}"; files were created.`);
    return;
  }

  const tuple = `  [\n    { id: '${slug}', name: '${displayName}', version: '1.0.0', enabled: true },\n    () => import('../../plugins/${slug}/index.jsx'),\n  ],\n\n`;

  const marker = '// ── Add more renderer plugins here ───────────────────────────────────────';
  if (loader.includes(marker)) {
    loader = loader.replace(marker, `${tuple}  ${marker}`);
    fs.writeFileSync(loaderPath, loader);
    return;
  }

  const arrayStart = loader.indexOf('const ACTIVE_RENDERER_PLUGINS = [');
  assert(arrayStart !== -1, 'Could not find ACTIVE_RENDERER_PLUGINS array in rendererPluginLoader.js');

  const arrayEnd = loader.indexOf('];', arrayStart);
  assert(arrayEnd !== -1, 'Could not find end of ACTIVE_RENDERER_PLUGINS array in rendererPluginLoader.js');

  loader = `${loader.slice(0, arrayEnd)}${tuple}${loader.slice(arrayEnd)}`;
  fs.writeFileSync(loaderPath, loader);
}

function askPluginNameFromCli() {
  return new Promise((resolve) => {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });

    rl.question('Enter plugin name: ', (answer) => {
      rl.close();
      resolve((answer || '').trim());
    });
  });
}

async function main() {
  let rawName = process.argv.slice(2).join(' ').trim();

  if (!rawName) {
    rawName = await askPluginNameFromCli();
  }

  assert(rawName, 'Missing plugin name. Usage: npm run plugin:new -- "my-plugin"');

  const slug = slugify(rawName);
  assert(slug, 'Plugin name produced an empty id. Use letters or numbers.');

  const displayName = toTitleCaseFromSlug(slug);

  createPluginFiles(slug, displayName);
  wirePluginIntoRendererLoader(slug, displayName);

  console.log('[plugin:new] Plugin scaffold created successfully');
  console.log(`[plugin:new] id: ${slug}`);
  console.log(`[plugin:new] folder: src/plugins/${slug}`);
}

main();
